### ISSUE TITLE
Learn what conventional commits

### ISSUE THREAD

**Issue by petterik** [eponai/tools.cursive-arcadia-repl#7]
Ping @dnegma about it

**Comment by dnegma** [comment]
Use a naming convention so that we can automatically generate changelogs later. 

Commit message structure: 
```
<type>[optional scope]: <description>

[optional body]

[optional footer]
```

Where `type` is one of the following copied from [conventionalcommits.org](https://www.conventionalcommits.org/en/v1.0.0-beta.4/):

1. `fix:` a commit of the type fix patches a bug in your codebase (this correlates with PATCH in semantic versioning).
2. `feat:` a commit of the type feat introduces a new feature to the codebase (this correlates with MINOR in semantic versioning).
3. `BREAKING CHANGE:` a commit that has the text BREAKING CHANGE: at the beginning of its optional body or footer section introduces a breaking API change (correlating with MAJOR in semantic versioning). A `BREAKING CHANGE` can be part of commits of any type.
4. Others: commit types other than fix: and feat: are allowed, for example @commitlint/config-conventional (based on the the Angular convention) recommends `chore:`, `docs:`, `style:`, `refactor:`, `perf:`, `test:`, and others.

See full more on : https://www.conventionalcommits.org/en/v1.0.0-beta.4/

**Comment by petterik** [comment]
Thanks for the summary, @dnegma! 🙂

Done reading through conventionalcommits.org. Closing.
